// Mantener las interfaces originales para compatibilidad
interface Currency {
  code: string;
  name: string;
  symbol: string;
  format: string;
  flag?: string;
}

interface CountryTax {
  countryCode?: string;
  countryName?: string;
  rate: number;
  name: string;
  abbreviation: string;
}

interface Country {
  code: string;
  name: string;
  symbol: string;
  format: string;
  flag: string;
  phoneCode: string;
}

// Interfaz unificada que contiene toda la información de cada país
interface UnifiedCountryData {
  // Información básica del país
  code: string;
  name: string;
  flag: string;
  phoneCode: string;

  // Información de moneda
  currency: Currency;

  // Información de impuestos
  tax: CountryTax;
}

// Array unificado con toda la información de cada país
export const unifiedCountriesData: UnifiedCountryData[] = [
  // Países latinoamericanos
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    phoneCode: "+54",
    currency: {
      code: "ARS",
      name: "Peso argentino",
      symbol: "AR$",
      format: "AR$0,0.00",
    },
    tax: {
      rate: 0.21,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "BO",
    name: "Bolivia",
    flag: "🇧🇴",
    phoneCode: "+591",
    currency: {
      code: "BOB",
      name: "Boliviano",
      symbol: "Bs",
      format: "Bs0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "BR",
    name: "Brasil",
    flag: "🇧🇷",
    phoneCode: "+55",
    currency: {
      code: "BRL",
      name: "Real brasileño",
      symbol: "R$",
      format: "R$0,0.00",
    },
    tax: {
      rate: 0.17,
      name: "Imposto sobre Circulação de Mercadorias e Serviços",
      abbreviation: "ICMS",
    },
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    phoneCode: "+56",
    currency: {
      code: "CLP",
      name: "Peso chileno",
      symbol: "CLP$",
      format: "CLP$0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    phoneCode: "+57",
    currency: {
      code: "COP",
      name: "Peso colombiano",
      symbol: "COL$",
      format: "COL$0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    phoneCode: "+506",
    currency: {
      code: "CRC",
      name: "Colón costarricense",
      symbol: "₡",
      format: "₡0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Impuesto General sobre las Ventas",
      abbreviation: "IGV",
    },
  },
  {
    code: "CU",
    name: "Cuba",
    flag: "🇨🇺",
    phoneCode: "+53",
    currency: {
      code: "CUP",
      name: "Peso cubano",
      symbol: "CUP$",
      format: "CUP$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "DO",
    name: "República Dominicana",
    flag: "🇩🇴",
    phoneCode: "+1",
    currency: {
      code: "DOP",
      name: "Peso dominicano",
      symbol: "RD$",
      format: "RD$0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Impuesto a las Transferencias de Bienes Industrializados y Servicios",
      abbreviation: "ITBIS",
    },
  },
  {
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    phoneCode: "+593",
    currency: {
      code: "USD",
      name: "Dólar estadounidense",
      symbol: "US$",
      format: "US$0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "SV",
    name: "El Salvador",
    flag: "🇸🇻",
    phoneCode: "+503",
    currency: {
      code: "USD",
      name: "Dólar estadounidense",
      symbol: "US$",
      format: "US$0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Impuesto a la Transferencia de Bienes Muebles y a la Prestación de Servicios",
      abbreviation: "IVA",
    },
  },
  {
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    phoneCode: "+502",
    currency: {
      code: "GTQ",
      name: "Quetzal guatemalteco",
      symbol: "Q",
      format: "Q0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "HT",
    name: "Haití",
    flag: "🇭🇹",
    phoneCode: "+509",
    currency: {
      code: "HTG",
      name: "Gourde haitiano",
      symbol: "G",
      format: "G0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Taxe sur la Valeur Ajoutée",
      abbreviation: "TVA",
    },
  },
  {
    code: "HN",
    name: "Honduras",
    flag: "🇭🇳",
    phoneCode: "+504",
    currency: {
      code: "HNL",
      name: "Lempira hondureño",
      symbol: "L",
      format: "L0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Impuesto Sobre Ventas",
      abbreviation: "ISV",
    },
  },
  {
    code: "MX",
    name: "México",
    flag: "🇲🇽",
    phoneCode: "+52",
    currency: {
      code: "MXN",
      name: "Peso mexicano",
      symbol: "MX$",
      format: "MX$0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "NI",
    name: "Nicaragua",
    flag: "🇳🇮",
    phoneCode: "+505",
    currency: {
      code: "NIO",
      name: "Córdoba nicaragüense",
      symbol: "C$",
      format: "C$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Impuesto General al Valor",
      abbreviation: "IGV",
    },
  },
  {
    code: "PA",
    name: "Panamá",
    flag: "🇵🇦",
    phoneCode: "+507",
    currency: {
      code: "PAB",
      name: "Balboa panameño",
      symbol: "B/.",
      format: "B/.0,0.00",
    },
    tax: {
      rate: 0.07,
      name: "Impuesto a las Transferencias de Bienes Corporales Muebles y la Prestación de Servicios",
      abbreviation: "ITBMS",
    },
  },
  {
    code: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
    phoneCode: "+595",
    currency: {
      code: "PYG",
      name: "Guaraní paraguayo",
      symbol: "₲",
      format: "₲0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "PE",
    name: "Perú",
    flag: "🇵🇪",
    phoneCode: "+51",
    currency: {
      code: "PEN",
      name: "Sol peruano",
      symbol: "S/",
      format: "S/0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Impuesto General a las Ventas",
      abbreviation: "IGV",
    },
  },
  {
    code: "PR",
    name: "Puerto Rico",
    flag: "🇵🇷",
    phoneCode: "+1",
    currency: {
      code: "USD",
      name: "Dólar estadounidense",
      symbol: "US$",
      format: "US$0,0.00",
    },
    tax: {
      rate: 0.115,
      name: "Impuesto sobre Ventas y Uso",
      abbreviation: "IVU",
    },
  },
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    phoneCode: "+598",
    currency: {
      code: "UYU",
      name: "Peso uruguayo",
      symbol: "$U",
      format: "$U0,0.00",
    },
    tax: {
      rate: 0.22,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },
  {
    code: "VE",
    name: "Venezuela",
    flag: "🇻🇪",
    phoneCode: "+58",
    currency: {
      code: "VES",
      name: "Bolívar soberano",
      symbol: "Bs.S",
      format: "Bs.S0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Impuesto al Valor Agregado",
      abbreviation: "IVA",
    },
  },

  // Países principales del mundo
  {
    code: "US",
    name: "Estados Unidos",
    flag: "🇺🇸",
    phoneCode: "+1",
    currency: {
      code: "USD",
      name: "Dólar estadounidense",
      symbol: "US$",
      format: "US$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sales Tax (Variable por Estado)",
      abbreviation: "ST",
    },
  },
  {
    code: "CA",
    name: "Canadá",
    flag: "🇨🇦",
    phoneCode: "+1",
    currency: {
      code: "CAD",
      name: "Dólar canadiense",
      symbol: "CA$",
      format: "CA$0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Goods and Services Tax / Harmonized Sales Tax",
      abbreviation: "GST/HST",
    },
  },
  {
    code: "GB",
    name: "Reino Unido",
    flag: "🇬🇧",
    phoneCode: "+44",
    currency: {
      code: "GBP",
      name: "Libra esterlina",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "DE",
    name: "Alemania",
    flag: "🇩🇪",
    phoneCode: "+49",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
      format: "€0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Mehrwertsteuer",
      abbreviation: "MwSt.",
    },
  },
  {
    code: "FR",
    name: "Francia",
    flag: "🇫🇷",
    phoneCode: "+33",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
      format: "€0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Taxe sur la Valeur Ajoutée",
      abbreviation: "TVA",
    },
  },
  {
    code: "ES",
    name: "España",
    flag: "🇪🇸",
    phoneCode: "+34",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
      format: "€0,0.00",
    },
    tax: {
      rate: 0.21,
      name: "Impuesto sobre el Valor Añadido",
      abbreviation: "IVA",
    },
  },
  {
    code: "IT",
    name: "Italia",
    flag: "🇮🇹",
    phoneCode: "+39",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
      format: "€0,0.00",
    },
    tax: {
      rate: 0.22,
      name: "Imposta sul Valore Aggiunto",
      abbreviation: "IVA",
    },
  },
  {
    code: "CN",
    name: "China",
    flag: "🇨🇳",
    phoneCode: "+86",
    currency: {
      code: "CNY",
      name: "Yuan chino",
      symbol: "CN¥",
      format: "CN¥0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "JP",
    name: "Japón",
    flag: "🇯🇵",
    phoneCode: "+81",
    currency: {
      code: "JPY",
      name: "Yen japonés",
      symbol: "¥",
      format: "¥0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Consumption Tax",
      abbreviation: "CT",
    },
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    phoneCode: "+91",
    currency: {
      code: "INR",
      name: "Rupia india",
      symbol: "₹",
      format: "₹0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    phoneCode: "+61",
    currency: {
      code: "AUD",
      name: "Dólar australiano",
      symbol: "A$",
      format: "A$0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },

  // Más países del mundo
  {
    code: "AE",
    name: "Emiratos Árabes Unidos",
    flag: "🇦🇪",
    phoneCode: "+971",
    currency: {
      code: "AED",
      name: "Dirham de Emiratos Árabes Unidos",
      symbol: "د.إ",
      format: "د.إ0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "AF",
    name: "Afganistán",
    flag: "🇦🇫",
    phoneCode: "+93",
    currency: {
      code: "AFN",
      name: "Afgani afgano",
      symbol: "؋",
      format: "؋0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Business Receipts Tax",
      abbreviation: "BRT",
    },
  },
  {
    code: "AL",
    name: "Albania",
    flag: "🇦🇱",
    phoneCode: "+355",
    currency: {
      code: "ALL",
      name: "Lek albanés",
      symbol: "L",
      format: "L0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "AM",
    name: "Armenia",
    flag: "🇦🇲",
    phoneCode: "+374",
    currency: {
      code: "AMD",
      name: "Dram armenio",
      symbol: "֏",
      format: "֏0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "AO",
    name: "Angola",
    flag: "🇦🇴",
    phoneCode: "+244",
    currency: {
      code: "AOA",
      name: "Kwanza angoleño",
      symbol: "Kz",
      format: "Kz0,0.00",
    },
    tax: {
      rate: 0.14,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "AW",
    name: "Aruba",
    flag: "🇦🇼",
    phoneCode: "+297",
    currency: {
      code: "AWG",
      name: "Florín arubeño",
      symbol: "Afl.",
      format: "Afl.0,0.00",
    },
    tax: {
      rate: 0.06,
      name: "Turnover Tax",
      abbreviation: "BBO",
    },
  },
  {
    code: "AZ",
    name: "Azerbaiyán",
    flag: "🇦🇿",
    phoneCode: "+994",
    currency: {
      code: "AZN",
      name: "Manat azerbaiyano",
      symbol: "₼",
      format: "₼0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BA",
    name: "Bosnia y Herzegovina",
    flag: "🇧🇦",
    phoneCode: "+387",
    currency: {
      code: "BAM",
      name: "Marco convertible",
      symbol: "KM",
      format: "KM0,0.00",
    },
    tax: {
      rate: 0.17,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BB",
    name: "Barbados",
    flag: "🇧🇧",
    phoneCode: "+1246",
    currency: {
      code: "BBD",
      name: "Dólar barbadense",
      symbol: "Bds$",
      format: "Bds$0,0.00",
    },
    tax: {
      rate: 0.175,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    phoneCode: "+880",
    currency: {
      code: "BDT",
      name: "Taka bangladesí",
      symbol: "৳",
      format: "৳0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    phoneCode: "+359",
    currency: {
      code: "BGN",
      name: "Lev búlgaro",
      symbol: "лв",
      format: "лв0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BH",
    name: "Baréin",
    flag: "🇧🇭",
    phoneCode: "+973",
    currency: {
      code: "BHD",
      name: "Dinar bahreiní",
      symbol: ".د.ب",
      format: ".د.ب0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BI",
    name: "Burundi",
    flag: "🇧🇮",
    phoneCode: "+257",
    currency: {
      code: "BIF",
      name: "Franco burundés",
      symbol: "FBu",
      format: "FBu0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BM",
    name: "Bermudas",
    flag: "🇧🇲",
    phoneCode: "+1441",
    currency: {
      code: "BMD",
      name: "Dólar bermudeño",
      symbol: "BD$",
      format: "BD$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "BN",
    name: "Brunéi",
    flag: "🇧🇳",
    phoneCode: "+673",
    currency: {
      code: "BND",
      name: "Dólar de Brunéi",
      symbol: "B$",
      format: "B$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "BS",
    name: "Bahamas",
    flag: "🇧🇸",
    phoneCode: "+1242",
    currency: {
      code: "BSD",
      name: "Dólar bahameño",
      symbol: "B$",
      format: "B$0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BT",
    name: "Bután",
    flag: "🇧🇹",
    phoneCode: "+975",
    currency: {
      code: "BTN",
      name: "Ngultrum butanés",
      symbol: "Nu.",
      format: "Nu.0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Sales Tax",
      abbreviation: "ST",
    },
  },
  {
    code: "BW",
    name: "Botsuana",
    flag: "🇧🇼",
    phoneCode: "+267",
    currency: {
      code: "BWP",
      name: "Pula botsuanesa",
      symbol: "P",
      format: "P0,0.00",
    },
    tax: {
      rate: 0.14,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BY",
    name: "Bielorrusia",
    flag: "🇧🇾",
    phoneCode: "+375",
    currency: {
      code: "BYN",
      name: "Rublo bielorruso",
      symbol: "Br",
      format: "Br0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "BZ",
    name: "Belice",
    flag: "🇧🇿",
    phoneCode: "+501",
    currency: {
      code: "BZD",
      name: "Dólar beliceño",
      symbol: "BZ$",
      format: "BZ$0,0.00",
    },
    tax: {
      rate: 0.125,
      name: "General Sales Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "CD",
    name: "República Democrática del Congo",
    flag: "🇨🇩",
    phoneCode: "+243",
    currency: {
      code: "CDF",
      name: "Franco congoleño",
      symbol: "FC",
      format: "FC0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "CH",
    name: "Suiza",
    flag: "🇨🇭",
    phoneCode: "+41",
    currency: {
      code: "CHF",
      name: "Franco suizo",
      symbol: "CHF",
      format: "CHF0,0.00",
    },
    tax: {
      rate: 0.077,
      name: "Mehrwertsteuer",
      abbreviation: "MwSt",
    },
  },
  {
    code: "CV",
    name: "Cabo Verde",
    flag: "🇨🇻",
    phoneCode: "+238",
    currency: {
      code: "CVE",
      name: "Escudo caboverdiano",
      symbol: "​$",
      format: "​$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "CZ",
    name: "República Checa",
    flag: "🇨🇿",
    phoneCode: "+420",
    currency: {
      code: "CZK",
      name: "Corona checa",
      symbol: "Kč",
      format: "Kč0,0.00",
    },
    tax: {
      rate: 0.21,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "DJ",
    name: "Yibuti",
    flag: "🇩🇯",
    phoneCode: "+253",
    currency: {
      code: "DJF",
      name: "Franco yibutiano",
      symbol: "Fdj",
      format: "Fdj0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "DK",
    name: "Dinamarca",
    flag: "🇩🇰",
    phoneCode: "+45",
    currency: {
      code: "DKK",
      name: "Corona danesa",
      symbol: "kr",
      format: "kr0,0.00",
    },
    tax: {
      rate: 0.25,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "DZ",
    name: "Argelia",
    flag: "🇩🇿",
    phoneCode: "+213",
    currency: {
      code: "DZD",
      name: "Dinar argelino",
      symbol: "د.ج",
      format: "د.ج0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "EG",
    name: "Egipto",
    flag: "🇪🇬",
    phoneCode: "+20",
    currency: {
      code: "EGP",
      name: "Libra egipcia",
      symbol: "E£",
      format: "E£0,0.00",
    },
    tax: {
      rate: 0.14,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "ER",
    name: "Eritrea",
    flag: "🇪🇷",
    phoneCode: "+291",
    currency: {
      code: "ERN",
      name: "Nakfa eritreo",
      symbol: "Nfk",
      format: "Nfk0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Sales Tax",
      abbreviation: "ST",
    },
  },
  {
    code: "ET",
    name: "Etiopía",
    flag: "🇪🇹",
    phoneCode: "+251",
    currency: {
      code: "ETB",
      name: "Birr etíope",
      symbol: "Br",
      format: "Br0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "FJ",
    name: "Fiyi",
    flag: "🇫🇯",
    phoneCode: "+679",
    currency: {
      code: "FJD",
      name: "Dólar fiyiano",
      symbol: "FJ$",
      format: "FJ$0,0.00",
    },
    tax: {
      rate: 0.09,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "FK",
    name: "Islas Malvinas",
    flag: "🇫🇰",
    phoneCode: "+500",
    currency: {
      code: "FKP",
      name: "Libra malvinense",
      symbol: "FK£",
      format: "FK£0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "FO",
    name: "Islas Feroe",
    flag: "🇫🇴",
    phoneCode: "+298",
    currency: {
      code: "FOK",
      name: "Corona feroesa",
      symbol: "kr",
      format: "kr0,0.00",
    },
    tax: {
      rate: 0.25,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "GE",
    name: "Georgia",
    flag: "🇬🇪",
    phoneCode: "+995",
    currency: {
      code: "GEL",
      name: "Lari georgiano",
      symbol: "₾",
      format: "₾0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "GG",
    name: "Guernsey",
    flag: "🇬🇬",
    phoneCode: "+44",
    currency: {
      code: "GGP",
      name: "Libra de Guernsey",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    phoneCode: "+233",
    currency: {
      code: "GHS",
      name: "Cedi ghanés",
      symbol: "GH₵",
      format: "GH₵0,0.00",
    },
    tax: {
      rate: 0.125,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "GI",
    name: "Gibraltar",
    flag: "🇬🇮",
    phoneCode: "+350",
    currency: {
      code: "GIP",
      name: "Libra gibraltareña",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "GM",
    name: "Gambia",
    flag: "🇬🇲",
    phoneCode: "+220",
    currency: {
      code: "GMD",
      name: "Dalasi gambiano",
      symbol: "D",
      format: "D0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "GN",
    name: "Guinea",
    flag: "🇬🇳",
    phoneCode: "+224",
    currency: {
      code: "GNF",
      name: "Franco guineano",
      symbol: "FG",
      format: "FG0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "GY",
    name: "Guyana",
    flag: "🇬🇾",
    phoneCode: "+592",
    currency: {
      code: "GYD",
      name: "Dólar guyanés",
      symbol: "GY$",
      format: "GY$0,0.00",
    },
    tax: {
      rate: 0.14,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "HK",
    name: "Hong Kong",
    flag: "🇭🇰",
    phoneCode: "+852",
    currency: {
      code: "HKD",
      name: "Dólar de Hong Kong",
      symbol: "HK$",
      format: "HK$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "HR",
    name: "Croacia",
    flag: "🇭🇷",
    phoneCode: "+385",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
      format: "€0,0.00",
    },
    tax: {
      rate: 0.25,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "HU",
    name: "Hungría",
    flag: "🇭🇺",
    phoneCode: "+36",
    currency: {
      code: "HUF",
      name: "Forinto húngaro",
      symbol: "Ft",
      format: "Ft0,0.00",
    },
    tax: {
      rate: 0.27,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    phoneCode: "+62",
    currency: {
      code: "IDR",
      name: "Rupia indonesia",
      symbol: "Rp",
      format: "Rp0,0.00",
    },
    tax: {
      rate: 0.11,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "IL",
    name: "Israel",
    flag: "🇮🇱",
    phoneCode: "+972",
    currency: {
      code: "ILS",
      name: "Nuevo séquel israelí",
      symbol: "₪",
      format: "₪0,0.00",
    },
    tax: {
      rate: 0.17,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "IM",
    name: "Isla de Man",
    flag: "🇮🇲",
    phoneCode: "+44",
    currency: {
      code: "IMP",
      name: "Libra manesa",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "IQ",
    name: "Irak",
    flag: "🇮🇶",
    phoneCode: "+964",
    currency: {
      code: "IQD",
      name: "Dinar iraquí",
      symbol: "ع.د",
      format: "ع.د0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "IR",
    name: "Irán",
    flag: "🇮🇷",
    phoneCode: "+98",
    currency: {
      code: "IRR",
      name: "Rial iraní",
      symbol: "﷼",
      format: "﷼0,0.00",
    },
    tax: {
      rate: 0.09,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "IS",
    name: "Islandia",
    flag: "🇮🇸",
    phoneCode: "+354",
    currency: {
      code: "ISK",
      name: "Corona islandesa",
      symbol: "kr",
      format: "kr0,0.00",
    },
    tax: {
      rate: 0.24,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "JE",
    name: "Jersey",
    flag: "🇯🇪",
    phoneCode: "+44",
    currency: {
      code: "JEP",
      name: "Libra de Jersey",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "JM",
    name: "Jamaica",
    flag: "🇯🇲",
    phoneCode: "+1876",
    currency: {
      code: "JMD",
      name: "Dólar jamaiquino",
      symbol: "J$",
      format: "J$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "General Consumption Tax",
      abbreviation: "GCT",
    },
  },
  {
    code: "JO",
    name: "Jordania",
    flag: "🇯🇴",
    phoneCode: "+962",
    currency: {
      code: "JOD",
      name: "Dinar jordano",
      symbol: "JD",
      format: "JD0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "General Sales Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "KE",
    name: "Kenia",
    flag: "🇰🇪",
    phoneCode: "+254",
    currency: {
      code: "KES",
      name: "Chelín keniano",
      symbol: "KSh",
      format: "KSh0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "KG",
    name: "Kirguistán",
    flag: "🇰🇬",
    phoneCode: "+996",
    currency: {
      code: "KGS",
      name: "Som kirguís",
      symbol: "som",
      format: "som0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "KH",
    name: "Camboya",
    flag: "🇰🇭",
    phoneCode: "+855",
    currency: {
      code: "KHR",
      name: "Riel camboyano",
      symbol: "៛",
      format: "៛0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "KI",
    name: "Kiribati",
    flag: "🇰🇮",
    phoneCode: "+686",
    currency: {
      code: "KID",
      name: "Dólar de Kiribati",
      symbol: "$",
      format: "$0,0.00",
    },
    tax: {
      rate: 0.125,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "KM",
    name: "Comoras",
    flag: "🇰🇲",
    phoneCode: "+269",
    currency: {
      code: "KMF",
      name: "Franco comorense",
      symbol: "CF",
      format: "CF0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "General Consumption Tax",
      abbreviation: "GCT",
    },
  },
  {
    code: "KR",
    name: "Corea del Sur",
    flag: "🇰🇷",
    phoneCode: "+82",
    currency: {
      code: "KRW",
      name: "Won surcoreano",
      symbol: "₩",
      format: "₩0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    phoneCode: "+965",
    currency: {
      code: "KWD",
      name: "Dinar kuwaití",
      symbol: "KD",
      format: "KD0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "KY",
    name: "Islas Caimán",
    flag: "🇰🇾",
    phoneCode: "+1345",
    currency: {
      code: "KYD",
      name: "Dólar de las Islas Caimán",
      symbol: "CI$",
      format: "CI$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "KZ",
    name: "Kazajistán",
    flag: "🇰🇿",
    phoneCode: "+7",
    currency: {
      code: "KZT",
      name: "Tenge kazajo",
      symbol: "₸",
      format: "₸0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "LA",
    name: "Laos",
    flag: "🇱🇦",
    phoneCode: "+856",
    currency: {
      code: "LAK",
      name: "Kip laosiano",
      symbol: "₭",
      format: "₭0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "LB",
    name: "Líbano",
    flag: "🇱🇧",
    phoneCode: "+961",
    currency: {
      code: "LBP",
      name: "Libra libanesa",
      symbol: "ل.ل",
      format: "ل.ل0,0.00",
    },
    tax: {
      rate: 0.11,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    phoneCode: "+94",
    currency: {
      code: "LKR",
      name: "Rupia de Sri Lanka",
      symbol: "Rs",
      format: "Rs0,0.00",
    },
    tax: {
      rate: 0.08,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "LR",
    name: "Liberia",
    flag: "🇱🇷",
    phoneCode: "+231",
    currency: {
      code: "LRD",
      name: "Dólar liberiano",
      symbol: "L$",
      format: "L$0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "LS",
    name: "Lesoto",
    flag: "🇱🇸",
    phoneCode: "+266",
    currency: {
      code: "LSL",
      name: "Loti lesotense",
      symbol: "M",
      format: "M0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "LY",
    name: "Libia",
    flag: "🇱🇾",
    phoneCode: "+218",
    currency: {
      code: "LYD",
      name: "Dinar libio",
      symbol: "LD",
      format: "LD0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "MA",
    name: "Marruecos",
    flag: "🇲🇦",
    phoneCode: "+212",
    currency: {
      code: "MAD",
      name: "Dírham marroquí",
      symbol: "MAD",
      format: "MAD0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MD",
    name: "Moldavia",
    flag: "🇲🇩",
    phoneCode: "+373",
    currency: {
      code: "MDL",
      name: "Leu moldavo",
      symbol: "L",
      format: "L0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MG",
    name: "Madagascar",
    flag: "🇲🇬",
    phoneCode: "+261",
    currency: {
      code: "MGA",
      name: "Ariary malgache",
      symbol: "Ar",
      format: "Ar0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MK",
    name: "Macedonia del Norte",
    flag: "🇲🇰",
    phoneCode: "+389",
    currency: {
      code: "MKD",
      name: "Denar macedonio",
      symbol: "ден",
      format: "ден0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MM",
    name: "Myanmar",
    flag: "🇲🇲",
    phoneCode: "+95",
    currency: {
      code: "MMK",
      name: "Kyat birmano",
      symbol: "K",
      format: "K0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Commercial Tax",
      abbreviation: "CT",
    },
  },
  {
    code: "MN",
    name: "Mongolia",
    flag: "🇲🇳",
    phoneCode: "+976",
    currency: {
      code: "MNT",
      name: "Tugrik mongol",
      symbol: "₮",
      format: "₮0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MO",
    name: "Macao",
    flag: "🇲🇴",
    phoneCode: "+853",
    currency: {
      code: "MOP",
      name: "Pataca de Macao",
      symbol: "MOP$",
      format: "MOP$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "MR",
    name: "Mauritania",
    flag: "🇲🇷",
    phoneCode: "+222",
    currency: {
      code: "MRU",
      name: "Uguiya mauritano",
      symbol: "UM",
      format: "UM0,0.00",
    },
    tax: {
      rate: 0.14,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MU",
    name: "Mauricio",
    flag: "🇲🇺",
    phoneCode: "+230",
    currency: {
      code: "MUR",
      name: "Rupia mauriciana",
      symbol: "Rs",
      format: "Rs0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MV",
    name: "Maldivas",
    flag: "🇲🇻",
    phoneCode: "+960",
    currency: {
      code: "MVR",
      name: "Rufiyaa maldiva",
      symbol: "Rf",
      format: "Rf0,0.00",
    },
    tax: {
      rate: 0.06,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "MW",
    name: "Malaui",
    flag: "🇲🇼",
    phoneCode: "+265",
    currency: {
      code: "MWK",
      name: "Kwacha malauí",
      symbol: "MK",
      format: "MK0,0.00",
    },
    tax: {
      rate: 0.165,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "MY",
    name: "Malasia",
    flag: "🇲🇾",
    phoneCode: "+60",
    currency: {
      code: "MYR",
      name: "Ringgit malayo",
      symbol: "RM",
      format: "RM0,0.00",
    },
    tax: {
      rate: 0.06,
      name: "Sales and Service Tax",
      abbreviation: "SST",
    },
  },
  {
    code: "MZ",
    name: "Mozambique",
    flag: "🇲🇿",
    phoneCode: "+258",
    currency: {
      code: "MZN",
      name: "Metical mozambiqueño",
      symbol: "MT",
      format: "MT0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "NA",
    name: "Namibia",
    flag: "🇳🇦",
    phoneCode: "+264",
    currency: {
      code: "NAD",
      name: "Dólar namibio",
      symbol: "N$",
      format: "N$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    phoneCode: "+234",
    currency: {
      code: "NGN",
      name: "Naira nigeriana",
      symbol: "₦",
      format: "₦0,0.00",
    },
    tax: {
      rate: 0.075,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "NO",
    name: "Noruega",
    flag: "🇳🇴",
    phoneCode: "+47",
    currency: {
      code: "NOK",
      name: "Corona noruega",
      symbol: "kr",
      format: "kr0,0.00",
    },
    tax: {
      rate: 0.25,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "NP",
    name: "Nepal",
    flag: "🇳🇵",
    phoneCode: "+977",
    currency: {
      code: "NPR",
      name: "Rupia nepalí",
      symbol: "₨",
      format: "₨0,0.00",
    },
    tax: {
      rate: 0.13,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "NZ",
    name: "Nueva Zelanda",
    flag: "🇳🇿",
    phoneCode: "+64",
    currency: {
      code: "NZD",
      name: "Dólar neozelandés",
      symbol: "NZ$",
      format: "NZ$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "OM",
    name: "Omán",
    flag: "🇴🇲",
    phoneCode: "+968",
    currency: {
      code: "OMR",
      name: "Rial omaní",
      symbol: "ر.ع.",
      format: "ر.ع.0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "PG",
    name: "Papúa Nueva Guinea",
    flag: "🇵🇬",
    phoneCode: "+675",
    currency: {
      code: "PGK",
      name: "Kina papú",
      symbol: "K",
      format: "K0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "PH",
    name: "Filipinas",
    flag: "🇵🇭",
    phoneCode: "+63",
    currency: {
      code: "PHP",
      name: "Peso filipino",
      symbol: "₱",
      format: "₱0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "PK",
    name: "Pakistán",
    flag: "🇵🇰",
    phoneCode: "+92",
    currency: {
      code: "PKR",
      name: "Rupia pakistaní",
      symbol: "₨",
      format: "₨0,0.00",
    },
    tax: {
      rate: 0.17,
      name: "General Sales Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "PL",
    name: "Polonia",
    flag: "🇵🇱",
    phoneCode: "+48",
    currency: {
      code: "PLN",
      name: "Złoty polaco",
      symbol: "zł",
      format: "zł0,0.00",
    },
    tax: {
      rate: 0.23,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "QA",
    name: "Catar",
    flag: "🇶🇦",
    phoneCode: "+974",
    currency: {
      code: "QAR",
      name: "Riyal qatarí",
      symbol: "QR",
      format: "QR0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "RO",
    name: "Rumania",
    flag: "🇷🇴",
    phoneCode: "+40",
    currency: {
      code: "RON",
      name: "Leu rumano",
      symbol: "lei",
      format: "lei0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "RS",
    name: "Serbia",
    flag: "🇷🇸",
    phoneCode: "+381",
    currency: {
      code: "RSD",
      name: "Dinar serbio",
      symbol: "din.",
      format: "din.0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "RU",
    name: "Rusia",
    flag: "🇷🇺",
    phoneCode: "+7",
    currency: {
      code: "RUB",
      name: "Rublo ruso",
      symbol: "₽",
      format: "₽0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "RW",
    name: "Ruanda",
    flag: "🇷🇼",
    phoneCode: "+250",
    currency: {
      code: "RWF",
      name: "Franco ruandés",
      symbol: "FRw",
      format: "FRw0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SA",
    name: "Arabia Saudita",
    flag: "🇸🇦",
    phoneCode: "+966",
    currency: {
      code: "SAR",
      name: "Riyal saudí",
      symbol: "SR",
      format: "SR0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SB",
    name: "Islas Salomón",
    flag: "🇸🇧",
    phoneCode: "+677",
    currency: {
      code: "SBD",
      name: "Dólar de las Islas Salomón",
      symbol: "SI$",
      format: "SI$0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "SC",
    name: "Seychelles",
    flag: "🇸🇨",
    phoneCode: "+248",
    currency: {
      code: "SCR",
      name: "Rupia seychelense",
      symbol: "SR",
      format: "SR0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SD",
    name: "Sudán",
    flag: "🇸🇩",
    phoneCode: "+249",
    currency: {
      code: "SDG",
      name: "Libra sudanesa",
      symbol: "SDG",
      format: "SDG0,0.00",
    },
    tax: {
      rate: 0.17,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SE",
    name: "Suecia",
    flag: "🇸🇪",
    phoneCode: "+46",
    currency: {
      code: "SEK",
      name: "Corona sueca",
      symbol: "kr",
      format: "kr0,0.00",
    },
    tax: {
      rate: 0.25,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SG",
    name: "Singapur",
    flag: "🇸🇬",
    phoneCode: "+65",
    currency: {
      code: "SGD",
      name: "Dólar de Singapur",
      symbol: "S$",
      format: "S$0,0.00",
    },
    tax: {
      rate: 0.08,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "SH",
    name: "Santa Elena",
    flag: "🇸🇭",
    phoneCode: "+290",
    currency: {
      code: "SHP",
      name: "Libra de Santa Elena",
      symbol: "£",
      format: "£0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "SL",
    name: "Sierra Leona",
    flag: "🇸🇱",
    phoneCode: "+232",
    currency: {
      code: "SLE",
      name: "Leone de Sierra Leona",
      symbol: "Le",
      format: "Le0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Goods and Services Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "SO",
    name: "Somalia",
    flag: "🇸🇴",
    phoneCode: "+252",
    currency: {
      code: "SOS",
      name: "Chelín somalí",
      symbol: "Sh.So.",
      format: "Sh.So.0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "SR",
    name: "Surinam",
    flag: "🇸🇷",
    phoneCode: "+597",
    currency: {
      code: "SRD",
      name: "Dólar surinamés",
      symbol: "$",
      format: "$0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SS",
    name: "Sudán del Sur",
    flag: "🇸🇸",
    phoneCode: "+211",
    currency: {
      code: "SSP",
      name: "Libra sursudanesa",
      symbol: "SSP",
      format: "SSP0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Sales Tax",
      abbreviation: "ST",
    },
  },
  {
    code: "ST",
    name: "Santo Tomé y Príncipe",
    flag: "🇸🇹",
    phoneCode: "+239",
    currency: {
      code: "STN",
      name: "Dobra santotomense",
      symbol: "Db",
      format: "Db0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "SY",
    name: "Siria",
    flag: "🇸🇾",
    phoneCode: "+963",
    currency: {
      code: "SYP",
      name: "Libra siria",
      symbol: "LS",
      format: "LS0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "SZ",
    name: "Suazilandia",
    flag: "🇸🇿",
    phoneCode: "+268",
    currency: {
      code: "SZL",
      name: "Lilangeni suazi",
      symbol: "E",
      format: "E0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TH",
    name: "Tailandia",
    flag: "🇹🇭",
    phoneCode: "+66",
    currency: {
      code: "THB",
      name: "Baht tailandés",
      symbol: "฿",
      format: "฿0,0.00",
    },
    tax: {
      rate: 0.07,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TJ",
    name: "Tayikistán",
    flag: "🇹🇯",
    phoneCode: "+992",
    currency: {
      code: "TJS",
      name: "Somoni tayiko",
      symbol: "ЅМ",
      format: "ЅМ0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TM",
    name: "Turkmenistán",
    flag: "🇹🇲",
    phoneCode: "+993",
    currency: {
      code: "TMT",
      name: "Manat turcomano",
      symbol: "m",
      format: "m0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TN",
    name: "Túnez",
    flag: "🇹🇳",
    phoneCode: "+216",
    currency: {
      code: "TND",
      name: "Dinar tunecino",
      symbol: "DT",
      format: "DT0,0.00",
    },
    tax: {
      rate: 0.19,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TO",
    name: "Tonga",
    flag: "🇹🇴",
    phoneCode: "+676",
    currency: {
      code: "TOP",
      name: "Paʻanga tongano",
      symbol: "T$",
      format: "T$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Consumption Tax",
      abbreviation: "CT",
    },
  },
  {
    code: "TR",
    name: "Turquía",
    flag: "🇹🇷",
    phoneCode: "+90",
    currency: {
      code: "TRY",
      name: "Lira turca",
      symbol: "₺",
      format: "₺0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Katma Değer Vergisi",
      abbreviation: "KDV",
    },
  },
  {
    code: "TT",
    name: "Trinidad y Tobago",
    flag: "🇹🇹",
    phoneCode: "+1868",
    currency: {
      code: "TTD",
      name: "Dólar de Trinidad y Tobago",
      symbol: "TT$",
      format: "TT$0,0.00",
    },
    tax: {
      rate: 0.125,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TV",
    name: "Tuvalu",
    flag: "🇹🇻",
    phoneCode: "+688",
    currency: {
      code: "TVD",
      name: "Dólar tuvaluano",
      symbol: "$",
      format: "$0,0.00",
    },
    tax: {
      rate: 0.0,
      name: "Sin Impuesto",
      abbreviation: "N/A",
    },
  },
  {
    code: "TW",
    name: "Taiwán",
    flag: "🇹🇼",
    phoneCode: "+886",
    currency: {
      code: "TWD",
      name: "Nuevo dólar taiwanés",
      symbol: "NT$",
      format: "NT$0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    phoneCode: "+255",
    currency: {
      code: "TZS",
      name: "Chelín tanzano",
      symbol: "TSh",
      format: "TSh0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "UA",
    name: "Ucrania",
    flag: "🇺🇦",
    phoneCode: "+380",
    currency: {
      code: "UAH",
      name: "Grivna ucraniana",
      symbol: "₴",
      format: "₴0,0.00",
    },
    tax: {
      rate: 0.2,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    phoneCode: "+256",
    currency: {
      code: "UGX",
      name: "Chelín ugandés",
      symbol: "USh",
      format: "USh0,0.00",
    },
    tax: {
      rate: 0.18,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "UZ",
    name: "Uzbekistán",
    flag: "🇺🇿",
    phoneCode: "+998",
    currency: {
      code: "UZS",
      name: "Som uzbeko",
      symbol: "soʻm",
      format: "soʻm0,0.00",
    },
    tax: {
      rate: 0.12,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    phoneCode: "+84",
    currency: {
      code: "VND",
      name: "Đồng vietnamita",
      symbol: "₫",
      format: "₫0,0.00",
    },
    tax: {
      rate: 0.1,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "VU",
    name: "Vanuatu",
    flag: "🇻🇺",
    phoneCode: "+678",
    currency: {
      code: "VUV",
      name: "Vatu vanuatuense",
      symbol: "VT",
      format: "VT0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "WS",
    name: "Samoa",
    flag: "🇼🇸",
    phoneCode: "+685",
    currency: {
      code: "WST",
      name: "Tala samoana",
      symbol: "WS$",
      format: "WS$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Goods and Services Tax",
      abbreviation: "VAGST",
    },
  },
  {
    code: "YE",
    name: "Yemen",
    flag: "🇾🇪",
    phoneCode: "+967",
    currency: {
      code: "YER",
      name: "Rial yemení",
      symbol: "﷼",
      format: "﷼0,0.00",
    },
    tax: {
      rate: 0.05,
      name: "General Sales Tax",
      abbreviation: "GST",
    },
  },
  {
    code: "ZA",
    name: "Sudáfrica",
    flag: "🇿🇦",
    phoneCode: "+27",
    currency: {
      code: "ZAR",
      name: "Rand sudafricano",
      symbol: "R",
      format: "R0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "ZM",
    name: "Zambia",
    flag: "🇿🇲",
    phoneCode: "+260",
    currency: {
      code: "ZMW",
      name: "Kwacha zambiano",
      symbol: "ZK",
      format: "ZK0,0.00",
    },
    tax: {
      rate: 0.16,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
  {
    code: "ZW",
    name: "Zimbabue",
    flag: "🇿🇼",
    phoneCode: "+263",
    currency: {
      code: "ZWL",
      name: "Dólar zimbabuense",
      symbol: "Z$",
      format: "Z$0,0.00",
    },
    tax: {
      rate: 0.15,
      name: "Value Added Tax",
      abbreviation: "VAT",
    },
  },
];
